version: '2'
services:
    mysql:
        build: ./mysql
        container_name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: headers
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
        volumes_from:
        - data
    app:
        build: ./php
        container_name: app
        links:
        - mysql
        volumes_from:
        - data
    nginx:
        build: ./nginx
        container_name: nginx
        links:
        - app
        ports:
        - 80:80
        volumes_from:
        - data
    data:
        build: ./data
        container_name: data
        volumes:
        - ./app/:/var/www/html
        - ./database/:/var/lib/mysql
